// examples/with-solid/src/components/root.jsx
import {atom, getMyAtoms, select} from 'strangelove';
import {addSolidMyAtoms} from 'strangelove-solid';
import {createEffect} from 'solid-js';

export function Root() {
  addSolidMyAtoms(getMyAtoms());
  const nameAtom = atom('Aleksey');
  const familyAtom = atom('Smith');
  const fullname = select((get) => get(nameAtom) + ' ' + get(familyAtom));

  return (
    <div>
      <div>
        Name:
        <input
          value={nameAtom.solid.get()}
          onInput={(event) => {
            nameAtom.solid.set(event.target.value);
          }}
        />
        <div>{nameAtom.solid.get()}</div>
      </div>
      <div>
        Family:
        <input
          value={familyAtom.solid.get()}
          onInput={(event) => {
            familyAtom.solid.set(event.target.value);
          }}
        />
        <div>{familyAtom.solid.get()}</div>
      </div>
      <div>
        Fullname:
        <div>{fullname.solid.get()}</div>
      </div>
    </div>
  );
}

// examples/with-svelte/src/components/root.svelte
<script>
  import {getMyAtoms, atom, select} from 'strangelove';
  import {addSvelteMyAtoms} from 'strangelove-svelte';

  addSvelteMyAtoms(getMyAtoms());

  const nameAtom = atom('Aleksey');
  const name = nameAtom.svelte;
  const familyAtom = atom('Smith');
  const family = familyAtom.svelte;
  const fullnameAtom = select((get) => get(nameAtom) + ' ' + get(familyAtom));
  const fullname = fullnameAtom.svelte;
</script>

<div class={$$props.class}>
  <div>
    Name:
    <input bind:value={$name} />
    <div>{$name}</div>
  </div>
  <div>
    Family:
    <input bind:value={$family} />
    <div>{$family}</div>
  </div>
  <div>
    Fullname:
    <div>{$fullname}</div>
  </div>
</div>
